name: transportation 

dependencies:
  - IPython=5.3.0
  - python=3.6.1
  - numpy=1.11.2
  - pandas=0.20.1
  - matplotlib=2.0.2
  - seaborn=0.7.1
  - statsmodels=0.8.0
  - dbfread=2.0.7
  - plotly
  - basemap=1.0.7
  - pip:
    - watermark==1.5.0
    - sklearn
